# Primeiro estágio: Build da aplicação com Node.js
FROM node:18-alpine AS builder


# Copiar arquivos de dependências para criar cache
COPY package.json yarn.lock ./

# Instalar dependências
RUN yarn install --frozen-lockfile --force

# Verificar se node_modules foi criado corretamente
RUN ls -la && ls -la node_modules

# Copiar o restante do código para o container
COPY . .

# Executar o build da aplicação
RUN yarn build

# Segundo estágio: Configuração do Nginx
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /dist /usr/share/nginx/html

EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]
